name: Linux

on:
  push:
    branches:
      - develop
      - "stable/**"
  pull_request:
    branches:
      - develop
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y \
            qtbase5-dev \
            qttools5-dev \
            qttools5-dev-tools \
            qtmultimedia5-dev \
            libqt5sql5-sqlite \
            libqt5sql5-psql \
            libqt5svg5-dev \
            libqt5multimedia5-plugins \
            lintian \
            rpmlint \
            libxerces-c-dev \
            libxalan-c-dev
          cd ~
          mkdir ~/boost-tmp
          cd ~/boost-tmp
          wget https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2
          tar --bzip2 -xf boost_1_79_0.tar.bz2
          cd boost_1_79_0
          ./bootstrap.sh --prefix=/usr
          sudo ./b2 install
          cd ~
          sudo rm -rf ~/boost-tmp

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          umask 022
          cmake \
            DESTDIR=/usr \
            -DDO_RELEASE_BUILD=ON \
            -DNO_MESSING_WITH_FLAGS=ON \
            $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          make

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        env:
          CTEST_OUTPUT_ON_FAILURE: TRUE
          QT_QPA_PLATFORM: minimal
        run: |
          make test

      - name: Package
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          umask 022
          make changelog
          make package

      - name: LintianAndRmpLint
        continue-on-error: true
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: make package_lint

      - name: Upload Brewtarget Installers
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: brewtarget-${{matrix.os}}
          path: build/brewtarget*
          retention-days: 7

      - name: Recover Debris Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-results-${{matrix.os}}
          path: build
          retention-days: 1
